---
layout: post
title: "OpenShift and (AWS) IAM"
author: naikoob
tags: [aws, cloud, kubernetes, openshift]
---
:source-highlighter: rouge
:imagesdir: /blog/assets/img/2021-03-15-openshift-cloud-credentials
:icons: font
:page-liquid:

Let__'__s take a closer look at IAM credentials used by OpenShift on AWS.

== cloud credentials operator

OpenShift interacts with the underlying cloud infrastructure provider to perform operations such as provisioning additional worker nodes. To do this, OpenShift makes use of the https://docs.openshift.com/container-platform/4.7/authentication/managing_cloud_provider_credentials/about-cloud-credential-operator.html[Cloud Credential Operator] (CCO). The CCO operates on `CredentialsRequest` custom resource, and operates differently based on the `credentialMode` setting during installation.

== cco modes

By default, CCO operates in the `Mint` mode. In this mode, CCO creates (mints) new credentials based for components in the cluster. This allows it to create credentials with very specific permissions for the requesting component. However, this also means you need to provide an account with rights to create IAM users and roles to the CCO, which often raise concerns with enterprise security teams. 

An alternative is the `Manual` mode, where the CCO takes a backseat and user has to manage all the different credentials used by OpenShift. For version 4.7 of OpenShift, there are 5 credentials to manage as described in my link:{% post_url 2021-01-28-openshift-on-aws %}[earlier post].

A 3rd, `Passthrough` mode is available for OpenShift on AWS since version 4.5.8. In this mode, a single IAM credential will permissions to perform the different cluster functions is used for all components. Crucially, there is no permission to create new IAM users, roles, or policy, when using `Passthrough` mode, which should set security team at ease.

== credentialsrequest
